config/routes.rb
Diabeteslikeme::Application.routes.draw do

  resources :challenges


  resources :glucose_data


  resources :statuses

  resources :glucose_data do
    collection do
      post 'import'
    end
  end

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :authentications
  resources :statuses
  resources :tasks

  resources :users do
    member do
      get 'glucose_data'
    end
  end

  resource :profile, :controller => :profile do
    member do
      post 'single_update'
    end
  end

  match '/profile/public/:id' => 'profile#public', :as => 'public'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/mailbox' => 'mailbox#index'
  match '/calendar'  => 'calendar#index'
  root :to => "home#index"

end

app/controllers/glucose_data_controller.rb
class GlucoseDataController < InheritedResources::Base
  before_filter :authenticate_user!

  def index

  end

  def create
    if params[:glucose_datum]
      date = User::TO.to_date
      @glucose_datum = GlucoseDatum.new()
      @glucose_datum.user = current_user
      @glucose_datum.sensor_time = "#{date} #{params[:glucose_datum][:sensor_time]}"
      @glucose_datum.sensor_value = params[:glucose_datum][:sensor_value]
      @glucose_datum.save
    end
  end

  def import
    GlucoseDatum.import_glucose_data(params[:glucose_datum][:glucose_data_file], current_user)
    render :text => 'success'
  end
end

app/helpers/glucose_data_helper.rb
module GlucoseDataHelper
end

app/views/glucose_data/_form.html.erb
<%= simple_form_for(@glucose_datum) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/glucose_data/create.js.erb
var currentUserGlucoseData = <%=raw(current_user.get_glucose_data().to_json)%>;
drawChart();
$("#glucose_datum_sensor_value").val('')
$("#timepicker3").val('')

app/views/glucose_data/edit.html.erb
<h1>Editing glucose_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @glucose_datum %> |
<%= link_to 'Back', glucose_data_path %>

app/views/glucose_data/index.html.erb
<div class="left-sidebar">


  <div class="row-fluid">
    <div class="span6">
      <div class="container">
        <%= simple_form_for(:glucose_datum, :url => import_glucose_data_path, :wrapper => :bootstrap_moon_blue, :html => {:class => 'login-wrapper'}) do |f| %>
            <div class="content">
              <%= f.input :glucose_data_file, :as => :file, :placeholder => 'Glucose data', :input_html => {:class => 'span12'} %>
              <div class="actions">
                <%= f.button :submit, "Import", :class => 'btn-primary' %>
              </div>

            </div>
        <% end %>
      </div>
    </div>
  </div>


</div>

app/views/glucose_data/new.html.erb
<h1>New glucose_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', glucose_data_path %>

app/views/glucose_data/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_glucose_datum_path(@glucose_datum) %> |
<%= link_to 'Back', glucose_data_path %>