config/routes.rb
Diabeteslikeme::Application.routes.draw do

  resources :challenges


  resources :glucose_data


  resources :statuses

  resources :glucose_data do
    collection do
      post 'import'
    end
  end

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :authentications
  resources :statuses
  resources :tasks

  resources :users do
    member do
      get 'glucose_data'
    end
  end

  resource :profile, :controller => :profile do
    member do
      post 'single_update'
    end
  end

  match '/profile/public/:id' => 'profile#public', :as => 'public'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/mailbox' => 'mailbox#index'
  match '/calendar'  => 'calendar#index'
  root :to => "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :title, :due_date, :user
  belongs_to :challenge
  belongs_to :user
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.where(:user_id => current_user.id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="left-sidebar">
  <div class="row-fluid">
    <div class="span12">
      <div class="widget">
        <div class="widget-header">
          <div class="title">
            To Do Lis<a id="todo">t</a>
          </div>
                    <span class="tools">
                      <a class="fs1" aria-hidden="true" data-icon="&#xe090;"></a>
                    </span>
        </div>
        <div class="widget-body">
          <div class="todo-container">
            <ul class="todo-list" id='todolist'>
              <li class="new">
                <input type="checkbox" id="1"/>

                <label for="1">
                  Send flowers to Sandy
                            <span class="date">
                              Due Feb 14
                            </span>
                </label>
              </li>
              <li class="completed">
                <input type="checkbox" id="4"/>

                <label for="4">
                  Buy new iPad
                            <span class="date">
                              Due Feb 7
                            </span>
                </label>
              </li>
              <li class="process">
                <input type="checkbox" id="5" checked/>

                <label for="5">
                  Pay credit card bill
                            <span class="date">
                              Completed Jan 29
                            </span>
                </label>
              </li>
              <li class="new">
                <input type="checkbox" id="6"/>

                <label for="6">
                  Take a photograph
                            <span class="date">
                              Due Jan 30
                            </span>

                </label>
              </li>
              <li class="completed">
                <input type="checkbox" id="7"/>

                <label for="3">
                  Be creative
                            <span class="date">
                              Due Jan 22
                            </span>
                </label>
              </li>
              <li class="process">
                <input type="checkbox" id="8">

                <label for="2">
                  Have tea with the Queen
                            <span class="date">
                              Completed Jan 18
                            </span>
                </label>
              </li>
              <% @tasks.each do |task|  %>
                  <li>
                    <input type="checkbox">

                    <label for="2">
                      <%= task.title %>
                            <span class="date">
                              Completed <%= task.due_date %>
                            </span>
                    </label>
                  </li>
              <% end %>
            </ul>
            <form class="no-margin">
              <div class="input-append">
                <input id="add-new-task" class="input-block-level" type="text" placeholder="Add new task">
                          <span class="btn btn-info" id='add-task-btn'>
                            <strong>
                              +
                            </strong>
                          </span>
              </div>
            </form>
          </div>

        </div>
      </div>
    </div>
  </div>

</div>
<script type="text/javascript">
  $('#add-task-btn').addTask()
</script>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>