config/routes.rb
Diabeteslikeme::Application.routes.draw do

  resources :challenges


  resources :glucose_data


  resources :statuses

  resources :glucose_data do
    collection do
      post 'import'
    end
  end

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :authentications
  resources :statuses
  resources :tasks

  resources :users do
    member do
      get 'glucose_data'
    end
  end

  resource :profile, :controller => :profile do
    member do
      post 'single_update'
    end
  end

  match '/profile/public/:id' => 'profile#public', :as => 'public'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/mailbox' => 'mailbox#index'
  match '/calendar'  => 'calendar#index'
  root :to => "home#index"

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  attr_accessible :name, :duration, :description, :tasks_attributes, :owner
  belongs_to :owner, :class_name => 'User'
  has_many :tasks

  accepts_nested_attributes_for :tasks


end

app/controllers/challenges_controller.rb
class ChallengesController < InheritedResources::Base
  before_filter :build_tasks, :only => :new
  def collection
    Challenge.all
  end

  def create
    @challenge = Challenge.new(params[:challenge])
    @challenge.owner = current_user
    @challenge.tasks = @challenge.tasks.reject {|task| task.title.blank?}
    @challenge.tasks.each do |task|
      task.completed = false
      task.user = current_user
    end

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Question was successfully created.' }
        format.json { render json: @challenge, status: :created, location: @challenge }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  protected

  def build_tasks
    @challenge = Challenge.new
    3.times.each do
      @challenge.tasks << Task.new
    end
  end
  def begin_of_association_chain
    @current_user = current_user
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= simple_form_for(@challenge, :html => {:class => 'form-horizontal'}) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :description, :input_html => {:rows => 3} %>
    <%= f.input :duration, :input_html => {:class => 'date_picker'} %>
    <fieldset>
      <legend>Tasks</legend>
      <%= f.fields_for :tasks do |task| %>
          <%= task.input :title %>
          <%= task.input :due_date %>
      <% end %>
    </fieldset>
    <div class="form-actions">
      <%= f.button :submit, :class => 'primary-btn' %>
    </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<div class="left-sidebar">
  <div class="row-fluid">
    <div class="span12">
      <div class="widget">
        <div class="widget-header">
          <div class="title">
            Challenges
          </div>
                    <span class="tools">
                      <a class="btn btn-success" href="<%= new_challenge_url%>">
                        <i class="fs1 challenge-icon" aria-hidden="true" data-icon="" data-original-title=""></i> New Challenge
                      </a>
                    </span>
        </div>
        <div class="widget-body">
          <table class="table table-condensed table-striped table-bordered table-hover no-margin">
            <thead>
            <tr>
              <th style="width:45%">
                Name
              </th>
              <th style="width:20%" class="hidden-phone">
                Status
              </th>
              <th style="width:25%" class="hidden-phone">
                Duration
              </th>
              <th style="width:10%" class="hidden-phone">
              </th>
            </tr>
            </thead>
            <tbody>
            <% statues = %w(new completed challenging joined) %>
            <% map_class = {'new' => 'info', 'completed' => 'important', 'challenging' => 'success', 'joined' => 'warning'} %>
            <% collection.each do |resource| %>
                <% status = statues[rand(4)] %>
                <tr>
                  <td>
                            <span class="name">
                              <%= link_to(resource.name, resource) %>
                            </span>
                  </td>
                  <td>
                    <span class='label label-<%= map_class[status] %>'><%= status %></span>

                  </td>
                  <td class="hidden-phone">
                    <%= resource.duration %>
                  </td>
                  <td class="hidden-phone">

                    <div class="btn-group">
                      <% if status != 'joined' %>
                          <button class="btn btn-success">
                            <i class=" icon-white icon-heart"></i> Join
                          </button>
                      <% end %>
                    </div>
                  </td>

                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="right-sidebar">
  <div class="wrapper">
    <table class="table table-condensed table-striped table-bordered table-hover no-margin">
      <thead>
      <tr>
        <th colspan="3" style="text-align: center">
          <h6>Cycle to work</h6>
        </th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>
          1
        </td>
        <td>
                      <span class="name">
                        Mahendra Singh Dhoni
                      </span>
        </td>
        <td>
                      <span class="label label label-info">
                        900
                      </span>
        </td>
      </tr>
      <tr>
        <td>
          2
        </td>
        <td>
                      <span class="name">
                        Michel Clark
                      </span>
        </td>
        <td>
                      <span class="label label label-success">
                        891
                      </span>
        </td>
      </tr>
      <tr>
        <td>
          3
        </td>
        <td>
                      <span class="name">
                        Rahul Dravid
                      </span>
        </td>
        <td>
                      <span class="label label label-important">
                        811
                      </span>
        </td>
      </tr>
      <tr>
        <td>
          4
        </td>
        <td>
                      <span class="name">
                        Anthony Michell
                      </span>
        </td>
        <td>
                      <span class="label label label-info">
           712
                      </span>
        </td>

      </tr>
      <tr>
        <td>
          5
        </td>
        <td>
                      <span class="name">
                        Srinu Baswa
                      </span>
        </td>
        <td>
                      <span class="label label label-success">
                        711
                      </span>
        </td>

      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/challenges/new.html.erb
<h1>New challenge</h1>
<%= render 'form' %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>